### PR TITLE
[Work in progress]Try using cache to speed up the workflow

### PR DESCRIPTION
**Pull request by xinkeng0**
#### What this PR does / why we need it?
暂时固定，测试workflow中。
观察到workflwo的主要耗时集中在maven dowloading dependencies阶段，尝试使用Github Cache。
#### Please indicate you've done the following:

- [ ] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by xinkeng0** [comment]
您可以帮助我重新运行一次此action: https://github.com/metersphere/metersphere/actions/runs/8778053156/job/24083908051?pr=30483 吗？ @liuruibin

**Comment by liuruibin** [comment]
自上次pr合并后整个覆盖率统计时间缩短了2-3分钟，提升近15%

**Pull request merged**
