### PR TITLE
docs: 增加徽章

### PR DESCRIPTION
**Pull request by VictorZeng**
#### What this PR does / why we need it?

add  release version badges for README.md.

#### Summary of your change

add  release version badges for README.md.

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by VictorZeng** [comment]
Generic handler for MeterSphere Repos has a error, Seems to have no permissions. But I'dont konw why?
```shell
curl: (22) The requested URL returned error: 401
```

**Comment by wangzhen-fit2cloud** [comment]
> Generic handler for MeterSphere Repos has a error, Seems to have no permissions. But I'dont konw why?
> 
> ```shell
> curl: (22) The requested URL returned error: 401
> ```

This action use `GITHUBTOKEN` env from Repo secret, it failed because there's no such secret in your repo.
You can ignore this and we'll fix it later.

**Review by liuruibin — APPROVED** [review]
/approve
/lgtm

**Review by shiziyuan9527 — APPROVED** [review]

**Pull request merged**
