### PR TITLE
feat(登录):ldap启用时默认选择ldap登录方式

### PR DESCRIPTION
**Pull request by guhan121**
ldap启用时默认选择ldap登录方式

### CODE REVIEW

**Review by liuruibin — APPROVED** [review]

**Comment by liuruibin** [comment]
这一行没有分号 检查没有通过
image
[流泪]

**Comment by wangzhen-fit2cloud** [comment]
> 这一行没有分号 检查没有通过
> image
> [流泪]
> 上面那个CLA也要同意一下，我们以后也使用pr的方式开发

我直接修改了这个文件加了分号

**Comment by liuruibin** [comment]
> > 这一行没有分号 检查没有通过
> > image
> > [流泪]
> > 上面那个CLA也要同意一下，我们以后也使用pr的方式开发
> 
> 我直接修改了这个文件加了分号

image

**Comment by wangzhen-fit2cloud** [comment]
> ldap启用时默认选择ldap登录方式

@guhan121 你好，请处理下这个 CLA 协议

[CLA assistant check](https://cla-assistant.io/metersphere/metersphere?pullRequest=1754) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/metersphere/metersphere?pullRequest=1754) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: wangzhen-fit2cloud<br/>:x: qiantao<br/><hr/>**qiantao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/metersphere/metersphere?pullRequest=1754) it.</sub>

**Comment by guhan121** [comment]
用户错误

**Pull request closed without merging**
