### PR TITLE
chore: cleanup unnecessary console log

### PR DESCRIPTION
**Pull request by ruibaby**
Signed-off-by: Ryan Wang <i@ryanc.cc>

#### What this PR does / why we need it?

移除无用的 console log。

#### Summary of your change

移除无用的 console log。

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by JohnNiang** [comment]
> /cherrypick v1.20

Hi @wangzhen-fit2cloud ，可以根据[这里的配置](https://github.com/halo-dev/test-infra/blob/6a7c4298104ec965de4468910ed45f9be9263190/config/prow/plugins.yaml#L117-L124)为 metersphere 组织添加 cherrypicker 插件。

**Comment by wangzhen-fit2cloud** [comment]
> > /cherrypick v1.20
> 
> Hi @wangzhen-fit2cloud ，可以根据[这里的配置](https://github.com/halo-dev/test-infra/blob/6a7c4298104ec965de4468910ed45f9be9263190/config/prow/plugins.yaml#L117-L124)为 metersphere 组织添加 cherrypicker 插件。

已提交 [pull request](https://github.com/halo-dev/test-infra/pull/26)。

**Comment by ruibaby** [comment]
另外，建议通过 ESLint Prettier 等工具来规范代码，并设置 pre commit hook。在提交前检查这些格式和规范问题。

**Review by wangzhen-fit2cloud — APPROVED** [review]

**Review by liuruibin — COMMENTED** [review]
/approve

**Comment by ruibaby** [comment]
> @liuruibin: #14794 failed to apply on top of branch "v1.20":
> 
> ```
> Applying: chore: cleanup unnecessary console log
> Using index info to reconstruct a base tree...
> M	frontend/src/common/js/custom_field.js
> Falling back to patching base and 3-way merge...
> Auto-merging frontend/src/common/js/custom_field.js
> CONFLICT (content): Merge conflict in frontend/src/common/js/custom_field.js
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 chore: cleanup unnecessary console log
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```
> 
> In response to [this](https://github.com/metersphere/metersphere/pull/14794#issuecomment-1154843427):
> 
> > /cherrypick v1.20
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

/cc @JohnNiang

**Pull request merged**
