### PR TITLE
[Feature] Add same-site option

### PR DESCRIPTION
**Pull request by heyanlong**
#### What this PR does / why we need it?
Add same-site option 
#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by heyanlong** [comment]
CLA failure https://github.com/cla-assistant/cla-assistant/issues/890, so sign tomorrow

**Review by liuruibin — COMMENTED** [review]
这个是为了解决什么问题呢？

**Comment by heyanlong** [comment]
Higher or lower cookie security levels can be set.

**Comment by liuruibin** [comment]
感谢关注我们的项目，我们目前没有此方面的需求

**Pull request closed without merging**
